// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cjvsbrfkkqrcrzmwtjry.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNqdnNicmZra3FyY3J6bXd0anJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NTAwMjAsImV4cCI6MjA2NjAyNjAyMH0.0rldwI3Lm4mb8qTxw9ghCk8lAK0X54r1MVwHrkao8PE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);